language: rust
rust:
  - nightly
cache: cargo
services:
  - docker
env:
  global:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=realword
    - POSTGRES_PORT=5432
before_script:
  - cargo install diesel_cli --no-default-features --features postgres
  - ./scripts/init_db.sh
script:
  - cargo build
  - ./scripts/run_tests.sh
